In [ ]:
import numpy as np 
# We use only this package!

Dataset $(x_k,y_k)$ generation

In [ ]:
np.random.seed(10)
# 무작위 결과를 특정 값으로 고정, 항상 같은 난수들이 생성됨
# 난수를 예측 가능하도록 만들어주는 역할

x = np.random.randn(10)
# 평균 0, 표준편차 1을 가지는 정규분포에서 난수 10개를 생성

y = 3*x + 2 + np.random.randn(10)
# y = 3*x + 2 + noise의 형태]
# x 값에 선형 변환을 적용한 후 랜덤 노이즈를 추가한 값

In [ ]:
print(x)
print(y)
# 생성된 x와 y 값을 출력

[ 1.3315865   0.71527897 -1.54540029 -0.00838385  0.62133597 -0.72008556
  0.26551159  0.10854853  0.00429143 -0.17460021]
[ 6.4277857   5.3488743  -3.60126655  3.00312253  4.09263805  0.28488093
  1.65993255  2.46078246  3.49741129  0.39639448]


Curve fit with linear function $f(x;\beta)=\beta_1x+\beta_2$

Define $E_2 = \sum_{k=1}^{10}(y_k-f(x_k;\beta))^2$

Then, we derive the following system of linear eqns $A\beta=y$ from $\partial_{\beta_i}E_2=0$:

$\begin{equation}
\left(\begin{matrix}
\sum_{k=1}^{n}x_{k}^{2} & \sum_{k=1}^{n}x_{k} \\
\sum_{k=1}^{n}x_{k} & n \\
\end{matrix}\right)\left(\begin{matrix}
\beta_{1} \\
\beta_{2} \\
\end{matrix}\right)=\left(\begin{matrix}
\sum_{k=1}^{n}x_{k}y_{k} \\
\sum_{k=1}^{n}y_{k} \\
\end{matrix}\right)
\end{equation}$

Initialize

$\begin{equation}
A = \left(\begin{matrix}
0 & 0 \\
0 & 0 \\
\end{matrix}\right)
\end{equation}$

In [ ]:
A= np.zeros((2,2))
print(A)
# A는 2×2 크기의 행렬이며, 모든 요소가 0

[[0. 0.]
 [0. 0.]]


Fill the diagonal components in $A$ with $\sum_{k=1}^{n}x_{k}^{2}$ and $n$

$\begin{equation}
A = \left(\begin{matrix}
\sum_{k=1}^{n}x_{k}^{2} & 0 \\
0 & n \\
\end{matrix}\right)
\end{equation}$

In [ ]:
A[0,0] = np.sum(x**2)
# A[0,0]에 x 값들의 제곱합을 저장
A[1,1] = len(x)
# A[1,1]에 x의 길이(10)를 저장
print(A)

[[ 5.69044342  0.        ]
 [ 0.         10.        ]]


Fill the offdiagonal component in $A$ with $\sum_{k=1}^{n}x_{k}$

$\begin{equation}
A = \left(\begin{matrix}
\sum_{k=1}^{n}x_{k}^{2} & \sum_{k=1}^{n}x_{k} \\
\sum_{k=1}^{n}x_{k} & 0 \\
\end{matrix}\right)
\end{equation}$

cf)(mathematics) 'offdiagonal' is not an element on the diagonal of a square matrix

In [ ]:
A[[0,1],[1,0]] = np.sum(x)
# A[0,1]과 A[1,0] 두 위치에 x 값들의 합을 저장
# [[sum(x^2)  sum(x) ]
#  [sum(x)    len(x)]]  형태가 됨, 선형 회귀 정규방정식에서 사용되는 행렬 형태

In [7]:
print(A)

[[ 5.69044342  0.59808308]
 [ 0.59808308 10.        ]]


Define

$\begin{equation}
y=\left(\begin{matrix}
\sum_{k=1}^{n}x_{k}y_{k} \\
\sum_{k=1}^{n}y_{k} \\
\end{matrix}\right)
\end{equation}$

In [ ]:
b = np.array([[np.inner(x,y)],[np.sum(y)]])
# 2×1 크기의 벡터
# b[0,0] = x와 y의 내적값
# b[1,0] = y 값들의 합

# Warning: x*y is different from np.inner(x,y), why?
# x * y는 요소별 곱셈, np.inner(x, y)는 벡터 내적

In [9]:
b

array([[20.91671923],
       [23.57055574]])

$\beta=A^{-1}b$

In [ ]:
A_inv = np.linalg.inv(A)
# A의 역행렬
# 만약 A가 역행렬이 존재하지 않는 경우 오류가 발생

In [ ]:
x = np.matmul(A_inv,b)
# Aθ=b를 풀기 위해 𝜃=𝐴^(−1) * 𝑏를 계산
# θ = [a, b] 형태로 y ≈ ax + b에 해당하는 선형 회귀 계수를 찾음

print(x)

# why does A_inv*b not use in the calcuation?
# A_inv * b는 일반적인 행렬 곱셈이 아닌 요소별 곱을 수행, 따라서 이 경우 유효하지 않은 결과를 반환함

[[3.44971387]
 [2.15073402]]


In [12]:
A_inv*b

array([[ 3.69901476, -0.22123181],
       [-0.24930089,  2.37196584]])

In [ ]:
b

# 결론적으로 x와 y는 선형 관계를 가지는 데이터로 생성됨
# A와 b를 구성하여 선형 회귀 방정식을 설정
# A_inv를 구해 θ = [a, b]를 계산하여 y = ax + b 형태의 최적 회귀 계수를 찾음

array([[20.91671923],
       [23.57055574]])